In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
file_path_train = '/home/shrey/Desktop/eye_data/train2.txt'
data = genfromtxt(file_path_train,delimiter=',')

In [3]:
data

array([[183., 121., 113., 371.],
       [178., 116., 163., 347.],
       [179., 121., 186., 349.],
       [171., 120., 280., 348.],
       [163., 117., 345., 343.],
       [186., 124., 109., 419.],
       [180., 121., 176., 412.],
       [173., 120., 236., 413.],
       [165., 119., 304., 415.],
       [160., 118., 355., 409.],
       [168., 118., 261., 444.],
       [177., 120., 172., 462.],
       [186., 123.,  89., 472.],
       [163., 116., 314., 452.],
       [171., 116., 230., 440.],
       [192., 130.,  62., 461.],
       [195., 134.,  35., 499.],
       [185., 130., 122., 523.],
       [161., 126., 374., 476.],
       [168., 127., 300., 490.],
       [188., 134.,  25., 630.],
       [169., 131., 229., 634.],
       [154., 128., 402., 618.],
       [186., 121.,  78., 357.],
       [163., 113., 328., 346.],
       [163., 140., 325., 698.],
       [184., 129., 122., 492.],
       [165., 128., 328., 509.],
       [173., 108., 193., 339.],
       [177., 121., 222., 348.],
       [16

In [4]:
# the first column of data represents x coordinate of eye centre
# second column represents y coordinate of eye centre
# third column represents x coordinate of target point
# fourth column represents y coordinate of target point
# here I use 3 random examples just for experimentation
# the original data needs to be stored in the required directory in .txt form separated with commas

In [5]:
X = data[:,[0,1]]
X

array([[183., 121.],
       [178., 116.],
       [179., 121.],
       [171., 120.],
       [163., 117.],
       [186., 124.],
       [180., 121.],
       [173., 120.],
       [165., 119.],
       [160., 118.],
       [168., 118.],
       [177., 120.],
       [186., 123.],
       [163., 116.],
       [171., 116.],
       [192., 130.],
       [195., 134.],
       [185., 130.],
       [161., 126.],
       [168., 127.],
       [188., 134.],
       [169., 131.],
       [154., 128.],
       [186., 121.],
       [163., 113.],
       [163., 140.],
       [184., 129.],
       [165., 128.],
       [173., 108.],
       [177., 121.],
       [161., 116.],
       [181., 129.]])

In [6]:
y1 = data[:,2]
y2 = data[:,3]

In [7]:
from sklearn.preprocessing import PolynomialFeatures
poly_features = PolynomialFeatures(degree=2,include_bias=False)
X_poly = poly_features.fit_transform(X)
X_poly.shape

(32, 5)

In [8]:
def normalize(data):
    mean = data.mean(axis=0)
    std = data.std(axis=0)
    data = (data-mean)/std
    return data,mean,std

In [9]:
X_poly_norm,mean,std = normalize(X_poly)
X_poly_norm

array([[ 8.56172689e-01, -2.86508703e-01,  8.44758081e-01,
         3.58489734e-01, -3.09214060e-01],
       [ 3.80521195e-01, -1.01414985e+00,  3.53287223e-01,
        -3.80804553e-01, -1.00380544e+00],
       [ 4.75651494e-01, -2.86508703e-01,  4.50492262e-01,
         1.19146299e-01, -3.09214060e-01],
       [-2.85390896e-01, -4.32036934e-01, -3.11900203e-01,
        -4.44101991e-01, -4.50476949e-01],
       [-1.04643329e+00, -8.68621624e-01, -1.03944044e+00,
        -1.16064876e+00, -8.67231778e-01],
       [ 1.14156359e+00,  1.50075987e-01,  1.14617539e+00,
         8.13934576e-01,  1.21608444e-01],
       [ 5.70781793e-01, -2.86508703e-01,  5.48241868e-01,
         1.78982158e-01, -3.09214060e-01],
       [-9.51302988e-02, -4.32036934e-01, -1.24569483e-01,
        -3.25419296e-01, -4.50476949e-01],
       [-8.56172689e-01, -5.77565164e-01, -8.60822779e-01,
        -8.81744428e-01, -5.90567531e-01],
       [-1.33182418e+00, -7.23093394e-01, -1.30328269e+00,
        -1.25510041e+00

In [10]:
from sklearn.linear_model import LinearRegression
lin_reg1 = LinearRegression()
lin_reg1.fit(X_poly_norm,y1)
lin_reg2 = LinearRegression()
lin_reg2.fit(X_poly_norm,y2)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
file_path_test = '/home/shrey/Desktop/eye_data/train2.txt'
data_test = genfromtxt(file_path_test,delimiter=',')
X_new = data_test[:,[0,1]]
y1_new = data_test[:,2]
y2_new = data_test[:,3]
X_new_poly = poly_features.fit_transform(X_new)
X_new_poly_norm = (X_new_poly - mean)/std
X_new_poly_norm

array([[ 8.56172689e-01, -2.86508703e-01,  8.44758081e-01,
         3.58489734e-01, -3.09214060e-01],
       [ 3.80521195e-01, -1.01414985e+00,  3.53287223e-01,
        -3.80804553e-01, -1.00380544e+00],
       [ 4.75651494e-01, -2.86508703e-01,  4.50492262e-01,
         1.19146299e-01, -3.09214060e-01],
       [-2.85390896e-01, -4.32036934e-01, -3.11900203e-01,
        -4.44101991e-01, -4.50476949e-01],
       [-1.04643329e+00, -8.68621624e-01, -1.03944044e+00,
        -1.16064876e+00, -8.67231778e-01],
       [ 1.14156359e+00,  1.50075987e-01,  1.14617539e+00,
         8.13934576e-01,  1.21608444e-01],
       [ 5.70781793e-01, -2.86508703e-01,  5.48241868e-01,
         1.78982158e-01, -3.09214060e-01],
       [-9.51302988e-02, -4.32036934e-01, -1.24569483e-01,
        -3.25419296e-01, -4.50476949e-01],
       [-8.56172689e-01, -5.77565164e-01, -8.60822779e-01,
        -8.81744428e-01, -5.90567531e-01],
       [-1.33182418e+00, -7.23093394e-01, -1.30328269e+00,
        -1.25510041e+00

In [23]:
diff1 = lin_reg1.predict(X_new_poly_norm)-y1_new
diff1

array([ 1.63199959e+01,  7.10101604e+00, -1.55085543e+01, -2.90479704e+01,
       -1.75848851e+01, -6.59198594e+00, -1.57865716e+01, -5.51682667e+00,
        6.64263661e+00,  4.91761873e+00,  1.71853980e+01,  1.74266991e+01,
        1.23061646e+01,  1.12329765e+01,  1.27730414e+01, -1.89135315e+01,
       -2.54954256e+01, -8.27403940e+00, -1.85169679e+01, -1.45662204e+01,
        5.44940651e+01,  4.31627279e+01,  2.12907482e+01,  2.03374921e+01,
       -1.08433859e+01, -1.77732797e+01,  2.26710118e+00, -1.32311001e+01,
       -2.86563644e-02, -3.09822103e+01,  5.74899221e+00, -4.54506242e+00])

In [24]:
diff2 = lin_reg2.predict(X_new_poly_norm)-y2_new
diff2

array([ 19.51987893,  10.34648548,  54.28480419,  69.23420306,
        69.84492837,  -2.12947941, -11.87319878,  -1.82523359,
        10.07451273,  21.2267528 , -37.19896456, -63.20993368,
       -67.66544591, -47.43473865, -59.99782326,  23.0766665 ,
        43.64540276, -17.80671964,  38.28852029,  19.13898672,
       -66.8327854 , -69.33820265, -60.30723699,  23.71358654,
        36.62819126,  38.76609303,   0.75914731,  21.74321861,
       -17.2144355 ,  61.53435342, -35.51548982,  -3.47604419])

In [14]:
(diff1**2).sum()/32

378.11153996641065

In [15]:
(diff2**2).sum()/32

1760.9297606303612

In [16]:
lin_reg1.intercept_,lin_reg1.coef_

(218.03124999999997,
 array([-128.3356691 ,  184.80809089,  -18.17374466,   61.9539815 ,
        -217.51248545]))

In [17]:
lin_reg2.intercept_,lin_reg2.coef_

(452.09375,
 array([ -39.54982622, -372.68966084,  -40.67868876,   76.55458944,
         412.56728427]))